### ISSUE TITLE
RBAC roles aren't recognized

### ISSUE THREAD

**Issue by milesmatthias** [GoogleCloudPlatform/gke-monitoring-tutorial#14]
When running `terraform apply`, the following error is displayed:

```
google_container_cluster.primary: Provisioning with 'local-exec'...
google_container_cluster.primary (local-exec): Executing: ["/bin/sh" "-c" "kubectl -n default apply -f ../manifests/rbac-setup.yaml --as=admin --as-group=system:masters"]
google_container_cluster.primary (local-exec): unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
google_container_cluster.primary (local-exec): unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ServiceAccount" in version "v1"
google_container_cluster.primary (local-exec): unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
```

The cluster is created successfully, however. The only thing possibly amiss is that there are no alerting policies. [According to the README](https://github.com/GoogleCloudPlatform/gke-monitoring-tutorial/blob/master/README.md#native-prometheus-integration), it appears there should be a Prometheus alert policy present after cluster creation.

Did a little googling on this and noticed most people see this error when running on k8s pre-RBAC (1.8), but I'm running on GKE with latest K8s:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.2-gke.9", GitCommit:"869cf55e493b5bc10ae080bdb3ac60338e868eff", GitTreeState:"clean", BuildDate:"2018-10-02T20:45:12Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by chrislovecnm** [comment]
Can you try this with kubectl 1.11.2?

**Comment by milesmatthias** [comment]
It works:

```console
google_container_cluster.primary: Provisioning with 'local-exec'...
google_container_cluster.primary (local-exec): Executing: ["/bin/sh" "-c" "echo 'KUBECTL VERSION' && kubectl version --client"]
google_container_cluster.primary (local-exec): KUBECTL VERSION
google_container_cluster.primary (local-exec): Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"archive", BuildDate:"2018-11-09T02:30:49Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
google_container_cluster.primary: Provisioning with 'local-exec'...
google_container_cluster.primary (local-exec): Executing: ["/bin/sh" "-c" "kubectl -n default apply -f ../manifests/rbac-setup.yaml --as=admin --as-group=system:masters"]
google_container_cluster.primary (local-exec): clusterrole.rbac.authorization.k8s.io/prometheus created
google_container_cluster.primary (local-exec): serviceaccount/prometheus created
google_container_cluster.primary (local-exec): clusterrolebinding.rbac.authorization.k8s.io/prometheus-stackdriver created
google_container_cluster.primary: Provisioning with 'local-exec'...
google_container_cluster.primary (local-exec): Executing: ["/bin/sh" "-c" "kubectl -n default apply -f ../manifests/prometheus-service-sed.yaml"]
google_container_cluster.primary (local-exec): service/prometheus created
google_container_cluster.primary (local-exec): deployment.extensions/prometheus created
google_container_cluster.primary (local-exec): configmap/prometheus created
google_container_cluster.primary: Provisioning with 'local-exec'...
google_container_cluster.primary (local-exec): Executing: ["/bin/sh" "-c" "sleep 120"]
google_container_cluster.primary: Creation complete after 5m49s (ID: stackdriver-monitoring-tutorial)
google_monitoring_alert_policy.prometheus_mem_alloc: Creating...
  combiner:                                           "" => "OR"
  conditions.#:                                       "" => "1"
  conditions.0.condition_threshold.#:                 "" => "1"
  conditions.0.condition_threshold.0.comparison:      "" => "COMPARISON_GT"
  conditions.0.condition_threshold.0.duration:        "" => "60s"
  conditions.0.condition_threshold.0.filter:          "" => "metric.type=\"external.googleapis.com/prometheus/go_memstats_alloc_bytes\" AND resource.type=\"k8s_container\""
  conditions.0.condition_threshold.0.threshold_value: "" => "12"
  conditions.0.display_name:                          "" => "mem alloc above 12"
  conditions.0.name:                                  "" => "<computed>"
  creation_record.#:                                  "" => "<computed>"
  display_name:                                       "" => "Prometheus mem alloc"
  enabled:                                            "" => "true"
  name:                                               "" => "<computed>"
  project:                                            "" => "<computed>"
google_monitoring_alert_policy.prometheus_mem_alloc: Creation complete after 1s (ID: projects/mmatthias-helmsman/alertPolicies/15351724402830278364)

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.

Outputs:

cluster_name = stackdriver-monitoring-tutorial
primary_zone = us-central1-a
```

**Comment by chrislovecnm** [comment]
Closing

**Comment by bkraizman** [comment]
Hello Chris,

Tried this demo and got the same error on rback-setup.yaml manifest, I believe it is related to K8S version. I see you recommend to use an older version? what about the newer versions?

**Comment by homernajafi** [comment]
It works for me:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}


$ make create
.......
Apply complete! Resources: 5 added, 0 changed, 0 destroyed.


$ kubectl get ClusterRoles | grep prometheus
prometheus                                                             3m39s
$ kubectl get ClusterRoleBinding | grep prometheus-stackdriver
prometheus-stackdriver                                 4m5s

**Comment by bkraizman** [comment]
Here is mine versions -
kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-dispatcher", GitCommit:"e3f5193e8f1091a162af7e17a781e6a3129bcfd0", GitTreeState:"clean", BuildDate:"2019-03-28T18:13:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.12", GitCommit:"06f08e60069231bd21bdf673cf0595aac80b99f6", GitTreeState:"clean", BuildDate:"2019-02-25T20:37:10Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

and I tried to run on GKE version - 1.11.7-gke.12, I am using GCP Cloud Shell, did not try from Mac or PC

**Comment by homernajafi** [comment]
Let me give it a try on CloudShell. I will let you know shortly.

**Comment by homernajafi** [comment]
CloudShell is also working for me. I am not really sure what can be wrong:


Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

Outputs:

cluster_name = stackdriver-monitoring-tutorial
primary_zone = us-west2-a
homernajafi@cloudshell:~/gke-monitoring-tutorial (homer-proj)$ kubectl get ClusterRoles | grep prometheus
prometheus                                                             2m33s
homernajafi@cloudshell:~/gke-monitoring-tutorial (homer-proj)$ kubectl get ClusterRoleBinding | grep prometheus-stackdriver
prometheus-stackdriver                                 2m43s
homernajafi@cloudshell:~/gke-monitoring-tutorial (homer-proj)$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:59:46Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
homernajafi@cloudshell:~/gke-monitoring-tutorial (homer-proj)$ gcloud config get-value  compute/zone
Your active configuration is: [cloudshell-10759]
us-west2-a

**Comment by masterbokj** [comment]
Tried using Mac and got the same error, maybe it is related kubectl version? I have the one that comes with Cloud SDK

google_container_cluster.primary (local-exec): Executing: ["/bin/sh" "-c" "kubectl -n default apply -f ../manifests/rbac-setup.yaml --as=admin --as-group=system:masters"]
google_container_cluster.primary (local-exec): unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
google_container_cluster.primary (local-exec): unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ServiceAccount" in version "v1"
google_container_cluster.primary (local-exec): unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"

**Comment by chrislovecnm** [comment]
I would guess kubectl version issue. What is the version on Mac?

**Comment by masterbokj** [comment]
I just tried with 1.14.0 and got the same error

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-gke.10", GitCommit:"aaf0906400b5fc1d858ce0566a571e4f3ed06b9f", GitTreeState:"clean", BuildDate:"2019-03-30T19:30:48Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

* google_container_cluster.primary: Error running command 'kubectl -n default apply -f ../manifests/rbac-setup.yaml --as=admin --as-group=system:masters': exit status 1. Output: unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ServiceAccount" in version "v1"
unable to recognize "../manifests/rbac-setup.yaml": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
