### ISSUE TITLE
Should Jenkins test with make or terraform?

### ISSUE THREAD

**Issue by milesmatthias** [GoogleCloudPlatform/gke-monitoring-tutorial#18]
https://github.com/GoogleCloudPlatform/gke-monitoring-tutorial/blob/44a004f787657b5e45e977778d26f070e2ffbae3/Jenkinsfile#L79

The instructions in the README tell people to do:

```
./scripts/generate-tfvars.sh
terraform init
terraform plan
terraform apply
terraform destroy
```

Should Jenkins run those steps to verify that when someone downloads this repo and tries to follow the instructions, everything will work? #17 is an example where following the instructions produced an error that `make` did not produce.

**Comment by chrislovecnm** [comment]
All our demos need to use make. Some of the docs are out of date.
