### ISSUE TITLE
in {README.md} file wrong pointer to bash script {generate-tfvars.sh}

### ISSUE THREAD

**Issue by aaarel** [GoogleCloudPlatform/gke-monitoring-tutorial#5]
Hi, after reviwing this tuturial i found that
in {README.md} file , section "Running Terraform"
there is a wrong pointer to bash script {generate-tfvars.sh}  script is inside /scripts folder and not /terraform 
Running Terraform
![image](https://user-images.githubusercontent.com/7408461/46656669-457be000-cbb7-11e8-96d4-284f7618d294.png)

**Comment by donovanjamesl** [comment]
Thanks.  We addressed the issue in pull request #8.
