### ISSUE TITLE
kubectl is needed but not mentioned 

### ISSUE THREAD

**Issue by aaarel** [GoogleCloudPlatform/gke-monitoring-tutorial#6]
Hi, after reviwing this tuturial i found that
in {README.md} file , section "Running Terraform"
we invoke the bash script {generate-tfvars.sh}  
when running it we require kubctl but this id not mentioned a a pre requisit
![image](https://user-images.githubusercontent.com/7408461/46656768-7b20c900-cbb7-11e8-8a09-3b536924dac8.png)

**Comment by chrislovecnm** [comment]
Thanks. Happy to have you contribute, otherwise we will update it.

**Comment by donovanjamesl** [comment]
[Thanks.  We addressed the issue in pull request #8.

**Comment by aaarel** [comment]
Thanks!
